apiVersion: v1
kind: ConfigMap
metadata:
  name: action-env
data:
  # TODO(giolekva): figure out how to use template "minio.fullname" .
  minio_addr: http://{{ .Values.minio.fullnameOverride }}:{{ .Values.minio.service.port }}
