apiVersion: v1
kind: Secret
metadata:
  name: minio-creds
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  accesskey: {{ .Values.accessKey | b64enc }}
  secretkey: {{ .Values.secretKey | b64enc }}
