apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - web
  routes:
  - kind: Rule
    match: Host(`{{ .Values.ingressHost }}`)
    services:
    - kind: Service
      # TODO(giolekva): figure out how to use template "minio.fullname" .
      name: {{ .Values.minio.fullnameOverride }}
      namespace: {{ .Release.Namespace }}
      passHostHeader: true
      port: {{ .Values.minio.service.port }}
