apiVersion: dodo.cloud.dodo.cloud/v1
kind: ResourceRenderer
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.secretName }}
  resourceTemplate: {{ toYaml .Values.resourceTemplate | indent 2 }}
