kind: Pod
apiVersion: v1
metadata:
  name: detect-faces
spec:
  containers:
  - name: detect-faces
    image: giolekva/face-detector:latest
    imagePullPolicy: Always
    command: ["python3", "main.py"]
    args: ["http://api.pcloud.svc:1111/graphql", "http://minio.minio.svc:9000", "0x3"]
  restartPolicy: Never
