apiVersion: v1
kind: Secret
metadata:
  name: ssh-key
type: Opaque
data:
  private: {{ .Values.sshPrivateKey }}
---
apiVersion: v1
kind: Service
metadata:
  name: dodo-app
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: dodo-app
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dodo-app
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: dodo-app
  replicas: 1
  template:
    metadata:
      labels:
        app: dodo-app
    spec:
      volumes:
      - name: ssh-key
        secret:
          secretName: ssh-key
      - name: env-config
        secret:
          secretName: env-config
      containers:
      - name: dodo-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        command:
        - pcloud-installer
        - dodo-app
        - --repo-addr={{ .Values.repoAddr }}
        - --ssh-key=/pcloud/ssh-key/private
        - --port=8080
        - --self={{ .Values.self }}
        - --namespace={{ .Values.namespace }} # TODO(gio): maybe use .Release.Namespace ?
        - --env-config=/pcloud/env-config/config.json
        volumeMounts:
        - name: ssh-key
          readOnly: true
          mountPath: /pcloud/ssh-key
        - name: env-config
          readOnly: true
          mountPath: /pcloud/env-config
---
apiVersion: v1
kind: Secret
metadata:
  name: env-config
type: Opaque
data:
  config.json: {{ .Values.envConfig }}
