apiVersion: v2
appVersion: 3.9.1
description: |-
    The Gerrit replica serves as a read-only Gerrit instance to serve repositories
    that it receives from a Gerrit instance via replication. It can be used to
    reduce the load on Gerrit instances.
name: gerrit-replica
version: 0.2.0
maintainers:
- name: Thomas Draebing
  email: thomas.draebing@sap.com
- name: Matthias Sohn
  email: matthias.sohn@sap.com
- name: Sasa Zivkov
  email: sasa.zivkov@sap.com
- name: Christian Halstrick
  email: christian.halstrick@sap.com
home: https://gerrit.googlesource.com/k8s-gerrit/+/master/helm-charts/gerrit-replica
icon: http://commondatastorage.googleapis.com/gerrit-static/diffy-w200.png
sources:
- https://gerrit.googlesource.com/k8s-gerrit/+/master
keywords:
- gerrit
- git
