image:
  repository: giolekva/pcloud-installer
  tag: latest
  pullPolicy: Always
port: 8080
apiPort: 8081
clusterRoleName: dodo-app-creator
repoAddr: 192.168.0.11
sshPrivateKey: key
self: ""
namespace: ""
envAppManagerAddr: ""
envConfig: ""
appAdminKey: ""
gitRepoPublicKey: ""
persistentVolumeClaimName: ""
