apiVersion: v1
kind: Service 
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Chart.Name }}
  ports:
    - nodePort: 
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.containerPort }}
