postInstall:
  callAction:
  - app: object-store
    action: create-bucket-with-webhook
    args: 
      WebhookURL: http://{{ .Chart.Name }}.{{ .Release.Namespace }}.svc:{{ .Values.servicePort }}/new_object
      BucketName: images