actions:
- name: detect-faces
  template: |
    kind: Pod
    apiVersion: v1
    metadata:
      name: detect-faces-{-{ .Id }-}
    spec:
      containers:
      - name: detect-faces
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        command: ["python3", "main.py"]
        args: [{-{ .PCloudApiAddr }-}, {-{ .ObjectStoreAddr }-}, {-{ .Id }-}]
      restartPolicy: Never
