accessKey: minio
secretKey: minio123
ingressHost: minio
minio:
  existingSecret: minio-creds
  fullnameOverride: minio
  image:
    repository: minio/minio
    tag: latest
    pullPolicy: Always
  persistence:
    size: 1Gi
minio_mc:
  image:
    repository: minio/mc
    tag: latest
    pullPolicy: Always
