{{ if .Values.adlists }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "pihole.fullname" . }}-adlists
  labels:
    app: {{ template "pihole.name" . }}
    chart: {{ template "pihole.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  adlists.list: |
  {{- range .Values.adlists }}
    {{ . }}
  {{- end }}
{{ end }}
