apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: dv-{{ .Values.name }}
spec:
  source:
    http:
      url: {{ .Values.disk.source }}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: {{ .Values.disk.size }}
