apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-processor
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: event-processor
  replicas: {{ .Values.replicas }}
  template:
    metadata:
      labels:
        app: event-processor
    spec:
      containers:
      - name: event-processor
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["event-processor", "--logtostderr", "--api_addr=http://api.pcloud.svc:1111/graphql", "--app_manager_addr=http://app-manager.pcloud-app-manager.svc:80", "--object_store_addr=http://minio.app-object-store.svc:9000"]
