apiVersion: v1
kind: Secret
metadata:
  name:  {{ .Release.Name }}-gerrit-replica-secure-config
  labels:
    app.kubernetes.io/component: gerrit-replica
    app.kubernetes.io/instance: {{ .Release.Name }}
    chart: {{ template "gerrit-replica.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels  | indent 4 }}
    {{- end }}
data:
  {{ if .Values.gerritReplica.keystore -}}
  keystore: {{ .Values.gerritReplica.keystore }}
  {{- end }}
  {{- range $key, $value := .Values.gerritReplica.etc.secret }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
type: Opaque
