[package]
name = "call_host"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
tui = {version = "0.18.0", default-features = false}
wasi = "0.11.0+wasi-snapshot-preview1"
